fix: train.py: "Value error: Input arrays should have the same number of..."
Error: "Value error: Input arrays should have the same number of samples as target arrays."

this was caused because when the data was formatted, the same variables were used, this should not be done, also made sure that trimmed data would never be 0